### ISSUE TITLE
install nightly rust on window and linux is always stable

### ISSUE THREAD

**Issue by foxundermoon** [xoac/rust-azure-pipelines#18]
just mac can install nightly

**Comment by foxundermoon** [comment]
```yaml
resources:
  repositories:
    - repository: templates
      type: github
      name: foxundermoon/rust-azure-pipelines
      ref: refs/heads/nightly ## TODO you may want to change it to refs/tags/TAG_NAME.
      endpoint: github_release


steps:
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: "Install rust (*nix)"
    condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

  # Windows.
  - script: |
      curl -sSf -o rustup-init.exe https://win.rustup.rs
      rustup-init.exe -y --default-toolchain nightly
      set PATH=%PATH%;%USERPROFILE%\.cargo\bin
      echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
    env:
      RUSTUP_TOOLCHAIN: nightly
    displayName: "Install rust (windows)"
    condition: eq(variables['Agent.OS'], 'Windows_NT')


  # All platforms.
  - script: |
        rustup -V
        rustup component list --installed
        rustc -Vv
        cargo -V
    displayName: Query rust and cargo versions
```


```log
##[section]Starting: Query rust and cargo versions
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.151.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
[command]/bin/bash --noprofile --norc /home/vsts/work/_temp/46f14fd7-851e-498e-b725-cdaca82699f1.sh
rustup 1.18.3 (435397f48 2019-05-22)
cargo-x86_64-unknown-linux-gnu
clippy-x86_64-unknown-linux-gnu
rust-docs-x86_64-unknown-linux-gnu
rust-std-x86_64-unknown-linux-gnu
rustc-x86_64-unknown-linux-gnu
rustfmt-x86_64-unknown-linux-gnu
rustc 1.35.0 (3c235d560 2019-05-20)
binary: rustc
commit-hash: 3c235d5600393dfe6c36eeed34042efad8d4f26e
commit-date: 2019-05-20
host: x86_64-unknown-linux-gnu
release: 1.35.0
LLVM version: 8.0
cargo 1.35.0 (6f3e9c367 2019-04-04)
##[section]Finishing: Query rust and cargo versions

```

https://dev.azure.com/marketing-cloud/yunpian-marketing-rest-mock/_build/results?buildId=16
