### ISSUE TITLE
Support githubRealese 

### ISSUE THREAD

**Issue by xoac** [xoac/rust-azure-pipelines#2]
Tracking issue for support github releases.

Azure has it build in:
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/github-release?view=azure-devops

What is should support:
- [ ] Allow build for many architectures
- [ ] Support archive

**Comment by xoac** [comment]
The configuration from azure-pipelines.yml could look like this:
```yaml
template: github-realese.yml@templates
paramteres:
  dependsOn:
    - cargo_test_stable
    - rustfmt
    - rust_clippy
  rust_version: stable
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
  contents: |
    rust-azure-pipelines # TODO binary name create by cargo build --realese
  targets: #TODO specify wanted targets
   - armv7-unknown-linux-musleabihf
   - x86_64-unknown-linux-gnu
   - x86_64-unknown-redox
   - x86_64-pc-windows-msvc
  github:
    gitHubConnection: xoac
    repositoryName: xoac/rust-azure-pipelines
```
